# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test package

on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    branches: [ develop ]
  repository_dispatch:
    types: deploy-develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js 14.4.0
      uses: actions/setup-node@v1
      with:
        node-version: '14.4.0'
    - name: Cache builds and folders
      uses: actions/cache@v2
      with:
        path: |
          ${{ github.workspace }}/.cache
          ${{ github.workspace }}/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}        
    - name: Clean install modules
      run: npm ci
    - name: Run test
      run: npm run test